name: blog-app

services:
  blog-my-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - blog-db-vol:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - blog-app-net
  blog-server:
    build:
      dockerfile: Dockerfile
      context: './'
    container_name: blog-app-container
    ports:
      - 3001:3000
    env_file:
      - ./.env
    volumes:
      - ./:/app
    depends_on:
      - blog-my-db
    networks:
      - blog-app-net

volumes:
  blog-db-vol:
networks:
  blog-app-net:

